export const TYPES = {
    SET_PROJECT_ITEMS: "SET_PROJECT_ITEMS",
    SET_PROJECT_ITEM: "SET_PROJECT_ITEM",
    DELETE_PROJECT_ITEM: "DELETE_PROJECT_ITEM",
    ADD_TASK: "ADD_TASK",
    GET_TASKS: "GET_TASKS",
}