export const TYPES = {
    SET_PROJECT_ITEMS: "SET_PROJECT_ITEMS",
    SET_PROJECT_ITEM: "SET_PROJECT_ITEM",
    DELETE_PROJECT_ITEM: "DELETE_PROJECT_ITEM",
    ADD_TASK: "ADD_TASK",
    GET_TASK_PAGE: "GET_TASK_PAGE",
}